id: IFE99948D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:33:06+00:00'
last_modified: '2022-06-07T14:09:33.196095+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14137
  title: གཏམ་མཛོད་མེས་པོའི་ཞལ་རྒྱུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '5746':
      image_group_id: I1KG14330
      title: ''
      total_pages: 388
      order: 1
      base_file: 5746.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
